=== PokemonTCG/pokemon-tcg-data/cards/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": { "type": "string" },
      "name": { "type": "string" },
      "supertype": {
        "enum": ["Pokémon", "Trainer", "Energy"]
      },
      "subtypes": {
        "type": "array",
        "items": {
          "enum": [ 
            "Basic",
            "Stage 1", 
            "Stage 2",
            "Baby",
            "Level-Up",
            "LEGEND",
            "MEGA",
            "EX",
            "GX",
            "BREAK",
            "Fusion Strike",
            "Rapid Strike",
            "Single Strike",
            "V",
            "VMAX",
            "VSTAR",
            "V-UNION",
            "Item",
            "Supporter",
            "Stadium",
            "Pokémon Tool",
            "Pokémon Tool F",
            "Rocket's Secret Machine",
            "Technical Machine",
            "Restored",
            "Goldenrod Game Corner",
            "TAG TEAM",
            "Special",
            "Prime",
            "Star",
            "Prism Star",
            "SP",
            "Radiant",
            "Eternamax"
          ]
        }
      },
      "number": { "type": "string" },
      "artist": { "type": "string" },
      "rarity": {
        "enum": [
          "Common",
          "Common Holo",
          "Uncommon",
          "Uncommon Holo",
          "Rare",
          "Rare Holo",
          "Rare ACE",
          "Rare BREAK",
          "Rare Prime",
          "Rare Holo LV.X",
          "Rare Holo EX",
          "Rare Holo GX",
          "Rare Holo Star",
          "Rare Holo V",
          "Rare Holo VMAX",
          "Rare Holo VSTAR",
          "Rare Prism Star",
          "Rare Shining",
          "Rare Shiny",
          "Rare Shiny GX",
          "Rare Ultra",
          "Rare Rainbow",
          "Rare Secret",
          "Amazing Rare",
          "Radiant Rare",
          "LEGEND",
          "V",
          "VM",
          "Promo",
          "Classic Collection"
        ]
      },
      "level": { "type": "string" },
      "hp": { "type": "string" },
      "types": { "$ref": "#/$defs/energies" },
      "evolvesFrom": { "type": "string" },
      "evolvesTo": {
        "type": "array",
        "items": { "type": "string" }
      },
      "abilities": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": { "type": "string" },
            "text": { "type": "string" },
            "type": { "type": "string" }
          },
          "required": [ "name", "text", "type" ]
        }
      },
      "attacks": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": { "type": "string" },
            "cost": { "$ref": "#/$defs/energies" },
            "convertedEnergyCost": { "type": "integer" },
            "damage": { "type": "string" },
            "text": { "type": "string" }
          },
          "required": [
            "name",
            "cost",
            "convertedEnergyCost",
            "damage",
            "text"
          ]
        }
      },
      "weaknesses": { "$ref": "#/$defs/energyValues" },
      "resistances": { "$ref": "#/$defs/energyValues" },
      "retreatCost": { "$ref": "#/$defs/energies" },
      "convertedRetreatCost": { "type": "integer" },
      "flavorText": { "type": "string" },
      "nationalPokedexNumbers": {
        "type": "array",
        "items": { "type": "integer" }
      },
      "legalities": {
        "type": "object",
        "properties": {
          "unlimited": { "enum": ["Legal", "Banned"] },
          "expanded": { "enum": ["Legal", "Banned"] },
          "standard": { "enum": ["Legal", "Banned"] }
        },
        "required": [ "unlimited" ]
      },
      "images": {
        "type": "object",
        "properties": {
          "large": { "type": "string" },
          "small": { "type": "string" }
        },
        "required": [ "large", "small" ]
      },
      "rules": {
        "type": "array",
        "items": { "type": "string" }
      },
      "ancientTrait": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "text": { "type": "string" }
        },
        "required": [ "name", "text" ]
      },
      "regulationMark": {
        "type": "string",
        "pattern": "[A-Z]"
      }
    },
    "required": [
      "id",
      "name",
      "supertype",
      "number",
      "images",
      "legalities"
    ]
  },

  "$defs": {
    "energy": { 
      "enum": [ 
        "[-]",
        "Colorless",
        "Darkness",
        "Dragon",
        "Fairy",
        "Fire",
        "Fighting",
        "Grass",
        "Lightning",
        "Metal",
        "Psychic",
        "Water",
        "Free"
      ]
    },
    "energies": {
      "type": "array",
      "items": { "$ref": "#/$defs/energy" }
    },
    "energyValues": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": { "$ref": "#/$defs/energy" },
          "value": { "type": "string" }
        },
        "required": [ "type", "value" ]
      }
    }
  }
}

=== PokemonTCG/pokemon-tcg-data/cards/en/tk1a.json
[
  {
    "id": "tk1a-1",
    "name": "Bagon",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ],
    "hp": "40",
    "types": [
      "Colorless"
    ],
    "evolvesTo": [
      "Shelgon"
    ],
    "attacks": [
      {
        "name": "Headbutt",
        "cost": [
          "Colorless"
        ],
        "convertedEnergyCost": 1,
        "damage": "10",
        "text": ""
      },
      {
        "name": "Flare",
        "cost": [
          "Fire",
          "Colorless"
        ],
        "convertedEnergyCost": 2,
        "damage": "20",
        "text": ""
      }
    ],
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "1",
    "artist": "Ken Sugimori",
    "nationalPokedexNumbers": [
      371
    ],
    "legalities": {
      "unlimited": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1a/1.png",
      "large": "https://images.pokemontcg.io/tk1a/1_hires.png"
    }
  },
  {
    "id": "tk1a-2",
    "name": "Combusken",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ],
    "hp": "70",
    "types": [
      "Fire"
    ],
    "evolvesFrom": "Torchic",
    "evolvesTo": [
      "Blaziken"
    ],
    "attacks": [
      {
        "name": "Flare",
        "cost": [
          "Fire"
        ],
        "convertedEnergyCost": 1,
        "damage": "20",
        "text": ""
      },
      {
        "name": "Double Kick",
        "cost": [
          "Colorless",
          "Colorless",
          "Colorless"
        ],
        "convertedEnergyCost": 3,
        "damage": "40×",
        "text": "Flip 2 coins. This attack does 40 damage times the number of heads."
      }
    ],
    "weaknesses": [
      {
        "type": "Water",
        "value": "×2"
      }
    ],
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "2",
    "artist": "Kouki Saitou",
    "nationalPokedexNumbers": [
      256
    ],
    "legalities": {
      "unlimited": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1a/2.png",
      "large": "https://images.pokemontcg.io/tk1a/2_hires.png"
    }
  },
  {
    "id": "tk1a-3",
    "name": "Delcatty",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ],
    "hp": "80",
    "types": [
      "Colorless"
    ],
    "evolvesFrom": "Skitty",
    "attacks": [
      {
        "name": "Scratch",
        "cost": [
          "Colorless",
          "Colorless"
        ],
        "convertedEnergyCost": 2,
        "damage": "30",
        "text": ""
      },
      {
        "name": "Ultra Energy Source",
        "cost": [
          "Colorless",
          "Colorless",
          "Colorless"
        ],
        "convertedEnergyCost": 3,
        "damage": "10×",
        "text": "Does 10 damage times the number of basic Energy cards attached to all of the Active Pokémon (both yours and your opponent's)."
      }
    ],
    "weaknesses": [
      {
        "type": "Fighting",
        "value": "×2"
      }
    ],
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "3",
    "artist": "Midori Harada",
    "nationalPokedexNumbers": [
      301
    ],
    "legalities": {
      "unlimited": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1a/3.png",
      "large": "https://images.pokemontcg.io/tk1a/3_hires.png"
    }
  },
  {
    "id": "tk1a-4",
    "name": "Latias",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ],
    "hp": "70",
    "types": [
      "Colorless"
    ],
    "attacks": [
      {
        "name": "Dragon Dew",
        "cost": [
          "Fire"
        ],
        "convertedEnergyCost": 1,
        "damage": "10",
        "text": "Remove 1 damage counter from 1 of your Pokémon"
      },
      {
        "name": "Heat Blast",
        "cost": [
          "Fire",
          "Fire",
          "Colorless"
        ],
        "convertedEnergyCost": 3,
        "damage": "40",
        "text": ""
      }
    ],
    "weaknesses": [
      {
        "type": "Psychic",
        "value": "×2"
      }
    ],
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "4",
    "artist": "Nakaoka",
    "nationalPokedexNumbers": [
      380
    ],
    "legalities": {
      "unlimited": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1a/4.png",
      "large": "https://images.pokemontcg.io/tk1a/4_hires.png"
    }
  },
  {
    "id": "tk1a-5",
    "name": "Numel",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ],
    "hp": "40",
    "types": [
      "Fire"
    ],
    "evolvesTo": [
      "Camerupt"
    ],
    "attacks": [
      {
        "name": "Firebreathing",
        "cost": [
          "Fire"
        ],
        "convertedEnergyCost": 1,
        "damage": "10+",
        "text": "Flip a coin. If heads, this attack does 10 damage plus 10 more damage."
      },
      {
        "name": "Tackle",
        "cost": [
          "Colorless",
          "Colorless"
        ],
        "convertedEnergyCost": 2,
        "damage": "20",
        "text": ""
      }
    ],
    "weaknesses": [
      {
        "type": "Water",
        "value": "×2"
      }
    ],
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "5",
    "artist": "Yuka Morii",
    "nationalPokedexNumbers": [
      322
    ],
    "legalities": {
      "unlimited": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1a/5.png",
      "large": "https://images.pokemontcg.io/tk1a/5_hires.png"
    }
  },
  {
    "id": "tk1a-6",
    "name": "Skitty",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ],
    "hp": "50",
    "types": [
      "Colorless"
    ],
    "evolvesTo": [
      "Delcatty"
    ],
    "attacks": [
      {
        "name": "Tackle",
        "cost": [
          "Colorless"
        ],
        "convertedEnergyCost": 1,
        "damage": "10",
        "text": ""
      },
      {
        "name": "Lunge",
        "cost": [
          "Colorless",
          "Colorless"
        ],
        "convertedEnergyCost": 2,
        "damage": "30",
        "text": "Flip a coin. If tails, this attack does nothing."
      }
    ],
    "weaknesses": [
      {
        "type": "Fighting",
        "value": "×2"
      }
    ],
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "6",
    "artist": "Atsuko Nishida",
    "nationalPokedexNumbers": [
      300
    ],
    "legalities": {
      "unlimited": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1a/6.png",
      "large": "https://images.pokemontcg.io/tk1a/6_hires.png"
    }
  },
  {
    "id": "tk1a-7",
    "name": "Torchic",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ],
    "hp": "50",
    "types": [
      "Fire"
    ],
    "evolvesTo": [
      "Combusken"
    ],
    "attacks": [
      {
        "name": "Firebreathing",
        "cost": [
          "Fire",
          "Colorless"
        ],
        "convertedEnergyCost": 2,
        "damage": "20+",
        "text": "Flip a coin. If heads, this attack does 20 damage plus 20 more damage."
      }
    ],
    "weaknesses": [
      {
        "type": "Water",
        "value": "×2"
      }
    ],
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "7",
    "artist": "Hironobu Yoshida",
    "nationalPokedexNumbers": [
      255
    ],
    "legalities": {
      "unlimited": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1a/7.png",
      "large": "https://images.pokemontcg.io/tk1a/7_hires.png"
    }
  },
  {
    "id": "tk1a-8",
    "name": "Potion",
    "supertype": "Trainer",
    "subtypes": [
      "Item"
    ],
    "rules": [
      "Remove 2 damage counters from 1 of your Pokémon (remove 1 damage counter if that Pokémon has only 1)."
    ],
    "number": "8",
    "artist": "Keiji Kinebuchi",
    "legalities": {
      "unlimited": "Legal",
      "standard": "Legal",
      "expanded": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1a/8.png",
      "large": "https://images.pokemontcg.io/tk1a/8_hires.png"
    }
  },
  {
    "id": "tk1a-9",
    "name": "Energy Search",
    "supertype": "Trainer",
    "subtypes": [
      "Item"
    ],
    "rules": [
      "Search your deck for a basic Energy card, show it to your opponent, and put it into your hand. Shuffle your deck afterward"
    ],
    "number": "9",
    "artist": "Kai Ishikawa",
    "legalities": {
      "unlimited": "Legal",
      "standard": "Legal",
      "expanded": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1a/9.png",
      "large": "https://images.pokemontcg.io/tk1a/9_hires.png"
    }
  },
  {
    "id": "tk1a-10",
    "name": "Fire Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ],
    "number": "10",
    "legalities": {
      "unlimited": "Legal",
      "standard": "Legal",
      "expanded": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1a/10.png",
      "large": "https://images.pokemontcg.io/tk1a/10_hires.png"
    }
  }
]

=== PokemonTCG/pokemon-tcg-data/cards/en/tk1b.json
[
  {
    "id": "tk1b-1",
    "name": "Electrike",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ],
    "hp": "50",
    "types": [
      "Lightning"
    ],
    "evolvesTo": [
      "Manectric"
    ],
    "attacks": [
      {
        "name": "Headbutt",
        "cost": [
          "Colorless"
        ],
        "convertedEnergyCost": 1,
        "damage": "10",
        "text": ""
      }
    ],
    "weaknesses": [
      {
        "type": "Fighting",
        "value": "×2"
      }
    ],
    "resistances": [
      {
        "type": "Metal",
        "value": "-30"
      }
    ],
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "1",
    "artist": "Ken Sugimori",
    "nationalPokedexNumbers": [
      309
    ],
    "legalities": {
      "unlimited": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1b/1.png",
      "large": "https://images.pokemontcg.io/tk1b/1_hires.png"
    }
  },
  {
    "id": "tk1b-2",
    "name": "Latios",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ],
    "hp": "80",
    "types": [
      "Colorless"
    ],
    "attacks": [
      {
        "name": "Gather Energy",
        "cost": [
          "Lightning",
          "Colorless"
        ],
        "convertedEnergyCost": 2,
        "damage": "20",
        "text": "Flip a coin. If heads, search your deck for a basic Energy card and attach it to 1 of your Pokémon. Shuffle your deck afterward."
      },
      {
        "name": "Dragon Claw",
        "cost": [
          "Lightning",
          "Lightning",
          "Colorless"
        ],
        "convertedEnergyCost": 3,
        "damage": "40",
        "text": ""
      }
    ],
    "weaknesses": [
      {
        "type": "Psychic",
        "value": "×2"
      }
    ],
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "2",
    "artist": "Kyoko Koizumi",
    "nationalPokedexNumbers": [
      381
    ],
    "legalities": {
      "unlimited": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1b/2.png",
      "large": "https://images.pokemontcg.io/tk1b/2_hires.png"
    }
  },
  {
    "id": "tk1b-3",
    "name": "Linoone",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ],
    "hp": "70",
    "types": [
      "Colorless"
    ],
    "evolvesFrom": "Zigzagoon",
    "attacks": [
      {
        "name": "Seek Out",
        "cost": [
          "Colorless"
        ],
        "convertedEnergyCost": 1,
        "damage": "",
        "text": "Search your deck for up to 2 cards and put them into your hand. Shuffle your deck afterward."
      },
      {
        "name": "Continuous Headbutt",
        "cost": [
          "Colorless",
          "Colorless"
        ],
        "convertedEnergyCost": 2,
        "damage": "40×",
        "text": "Flip a coin until you get tails. This attack does 40 damage times the number of heads."
      }
    ],
    "weaknesses": [
      {
        "type": "Fighting",
        "value": "×2"
      }
    ],
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "3",
    "artist": "Ken Sugimori",
    "nationalPokedexNumbers": [
      264
    ],
    "legalities": {
      "unlimited": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1b/3.png",
      "large": "https://images.pokemontcg.io/tk1b/3_hires.png"
    }
  },
  {
    "id": "tk1b-4",
    "name": "Magnemite",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ],
    "hp": "40",
    "types": [
      "Lightning"
    ],
    "evolvesTo": [
      "Magneton"
    ],
    "attacks": [
      {
        "name": "Rollout",
        "cost": [
          "Colorless"
        ],
        "convertedEnergyCost": 1,
        "damage": "10",
        "text": ""
      },
      {
        "name": "Hook",
        "cost": [
          "Colorless",
          "Colorless"
        ],
        "convertedEnergyCost": 2,
        "damage": "20",
        "text": ""
      }
    ],
    "weaknesses": [
      {
        "type": "Fighting",
        "value": "×2"
      }
    ],
    "resistances": [
      {
        "type": "Metal",
        "value": "-30"
      }
    ],
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "4",
    "artist": "Tomokazu Komiya",
    "nationalPokedexNumbers": [
      81
    ],
    "legalities": {
      "unlimited": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1b/4.png",
      "large": "https://images.pokemontcg.io/tk1b/4_hires.png"
    }
  },
  {
    "id": "tk1b-5",
    "name": "Magneton",
    "supertype": "Pokémon",
    "subtypes": [
      "Stage 1"
    ],
    "hp": "80",
    "types": [
      "Lightning"
    ],
    "evolvesFrom": "Magnemite",
    "evolvesTo": [
      "Magnezone"
    ],
    "attacks": [
      {
        "name": "Ram",
        "cost": [
          "Colorless",
          "Colorless"
        ],
        "convertedEnergyCost": 2,
        "damage": "20",
        "text": ""
      },
      {
        "name": "Triple Smash",
        "cost": [
          "Lightning",
          "Colorless",
          "Colorless"
        ],
        "convertedEnergyCost": 3,
        "damage": "20+",
        "text": "Flip 3 coins. This attack does 20 damage plus 20 more damage for each heads."
      }
    ],
    "weaknesses": [
      {
        "type": "Fighting",
        "value": "×2"
      }
    ],
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "5",
    "artist": "Kyoko Umemoto",
    "nationalPokedexNumbers": [
      82
    ],
    "legalities": {
      "unlimited": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1b/5.png",
      "large": "https://images.pokemontcg.io/tk1b/5_hires.png"
    }
  },
  {
    "id": "tk1b-6",
    "name": "Pikachu",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ],
    "hp": "50",
    "types": [
      "Lightning"
    ],
    "evolvesTo": [
      "Raichu"
    ],
    "attacks": [
      {
        "name": "Scratch",
        "cost": [
          "Colorless"
        ],
        "convertedEnergyCost": 1,
        "damage": "10",
        "text": ""
      },
      {
        "name": "Pika Bolt",
        "cost": [
          "Lightning",
          "Colorless",
          "Colorless"
        ],
        "convertedEnergyCost": 3,
        "damage": "40",
        "text": ""
      }
    ],
    "weaknesses": [
      {
        "type": "Fighting",
        "value": "×2"
      }
    ],
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "6",
    "artist": "Mitsuhiro Arita",
    "nationalPokedexNumbers": [
      25
    ],
    "legalities": {
      "unlimited": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1b/6.png",
      "large": "https://images.pokemontcg.io/tk1b/6_hires.png"
    }
  },
  {
    "id": "tk1b-7",
    "name": "Zigzagoon",
    "supertype": "Pokémon",
    "subtypes": [
      "Basic"
    ],
    "hp": "40",
    "types": [
      "Colorless"
    ],
    "evolvesTo": [
      "Linoone"
    ],
    "attacks": [
      {
        "name": "Fury Swipes",
        "cost": [
          "Colorless"
        ],
        "convertedEnergyCost": 1,
        "damage": "10×",
        "text": "Flip 3 coins. This attack does 10 damage times the number of heads."
      }
    ],
    "weaknesses": [
      {
        "type": "Fighting",
        "value": "×2"
      }
    ],
    "retreatCost": [
      "Colorless"
    ],
    "convertedRetreatCost": 1,
    "number": "7",
    "artist": "Atsuko Nishida",
    "nationalPokedexNumbers": [
      263
    ],
    "legalities": {
      "unlimited": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1b/7.png",
      "large": "https://images.pokemontcg.io/tk1b/7_hires.png"
    }
  },
  {
    "id": "tk1b-8",
    "name": "Potion",
    "supertype": "Trainer",
    "subtypes": [
      "Item"
    ],
    "rules": [
      "Remove 2 damage counters from 1 of your Pokémon (remove 1 damage counter if that Pokémon has only 1)."
    ],
    "number": "8",
    "artist": "Keiji Kinebuchi",
    "legalities": {
      "unlimited": "Legal",
      "standard": "Legal",
      "expanded": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1b/8.png",
      "large": "https://images.pokemontcg.io/tk1b/8_hires.png"
    }
  },
  {
    "id": "tk1b-9",
    "name": "Energy Search",
    "supertype": "Trainer",
    "subtypes": [
      "Item"
    ],
    "rules": [
      "Search your deck for a basic Energy card, show it to your opponent, and put it into your hand. Shuffle your deck afterward"
    ],
    "number": "9",
    "artist": "Kai Ishikawa",
    "legalities": {
      "unlimited": "Legal",
      "standard": "Legal",
      "expanded": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1b/9.png",
      "large": "https://images.pokemontcg.io/tk1b/9_hires.png"
    }
  },
  {
    "id": "tk1b-10",
    "name": "Lightning Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ],
    "number": "10",
    "legalities": {
      "unlimited": "Legal",
      "standard": "Legal",
      "expanded": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/tk1b/10.png",
      "large": "https://images.pokemontcg.io/tk1b/10_hires.png"
    }
  }
]

=== PokemonTCG/pokemon-tcg-data/cards/en/sve.json
[
  {
    "id": "sve-1",
    "name": "Basic Grass Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ],
    "number": "1",
    "rarity": "Common",
    "legalities": {
      "unlimited": "Legal",
      "standard": "Legal",
      "expanded": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/sve/1.png",
      "large": "https://images.pokemontcg.io/sve/1_hires.png"
    }
  },
  {
    "id": "sve-2",
    "name": "Basic Fire Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ],
    "number": "2",
    "rarity": "Common",
    "legalities": {
      "unlimited": "Legal",
      "standard": "Legal",
      "expanded": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/sve/2.png",
      "large": "https://images.pokemontcg.io/sve/2_hires.png"
    }
  },
  {
    "id": "sve-3",
    "name": "Basic Water Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ],
    "number": "3",
    "rarity": "Common",
    "legalities": {
      "unlimited": "Legal",
      "standard": "Legal",
      "expanded": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/sve/3.png",
      "large": "https://images.pokemontcg.io/sve/3_hires.png"
    }
  },
  {
    "id": "sve-4",
    "name": "Basic Lightning Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ],
    "number": "4",
    "rarity": "Common",
    "legalities": {
      "unlimited": "Legal",
      "standard": "Legal",
      "expanded": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/sve/4.png",
      "large": "https://images.pokemontcg.io/sve/4_hires.png"
    }
  },
  {
    "id": "sve-5",
    "name": "Basic Psychic Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ],
    "number": "5",
    "rarity": "Common",
    "legalities": {
      "unlimited": "Legal",
      "standard": "Legal",
      "expanded": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/sve/5.png",
      "large": "https://images.pokemontcg.io/sve/5_hires.png"
    }
  },
  {
    "id": "sve-6",
    "name": "Basic Fighting Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ],
    "number": "6",
    "rarity": "Common",
    "legalities": {
      "unlimited": "Legal",
      "standard": "Legal",
      "expanded": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/sve/6.png",
      "large": "https://images.pokemontcg.io/sve/6_hires.png"
    }
  },
  {
    "id": "sve-7",
    "name": "Basic Darkness Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ],
    "number": "7",
    "rarity": "Common",
    "legalities": {
      "unlimited": "Legal",
      "standard": "Legal",
      "expanded": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/sve/7.png",
      "large": "https://images.pokemontcg.io/sve/7_hires.png"
    }
  },
  {
    "id": "sve-8",
    "name": "Basic Metal Energy",
    "supertype": "Energy",
    "subtypes": [
      "Basic"
    ],
    "number": "8",
    "rarity": "Common",
    "legalities": {
      "unlimited": "Legal",
      "standard": "Legal",
      "expanded": "Legal"
    },
    "images": {
      "small": "https://images.pokemontcg.io/sve/8.png",
      "large": "https://images.pokemontcg.io/sve/8_hires.png"
    }
  }
]
