=== PokemonTCG/pokemon-tcg-data/decks/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": { "type": "string" },
      "name": { "type": "string" },
      "types": {
        "type": "array",
        "items": {
          "enum": [ 
            "Colorless",
            "Darkness",
            "Dragon",
            "Fairy",
            "Fire",
            "Fighting",
            "Grass",
            "Lightning",
            "Metal",
            "Psychic",
            "Water",
            "Free"
          ]
        }
      },
      "cards": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": { "type": "string" },
            "name": { "type": "string" },
            "rarity": {
              "enum": [
                "Common",
                "Common Holo",
                "Uncommon",
                "Uncommon Holo",
                "Rare",
                "Rare Holo",
                "Rare ACE",
                "Rare BREAK",
                "Rare Prime",
                "Rare Holo LV.X",
                "Rare Holo EX",
                "Rare Holo GX",
                "Rare Holo Star",
                "Rare Holo V",
                "Rare Holo VMAX",
                "Rare Holo VSTAR",
                "Rare Prism Star",
                "Rare Shining",
                "Rare Shiny",
                "Rare Shiny GX",
                "Rare Ultra",
                "Rare Rainbow",
                "Rare Secret",
                "Amazing Rare",
                "Radiant Rare",
                "LEGEND",
                "V",
                "VM",
                "Promo",
                "Classic Collection"
              ]
            },
            "count": { "type": "integer" }
          },
          "required": [ "id", "name", "count" ]
        }
      }
    },
    "required": [
      "id",
      "name",
      "types",
      "cards"
    ]
  }
}

=== PokemonTCG/pokemon-tcg-data/decks/en/ex8.json
[
  {
    "id": "d-ex8-1",
    "name": "Starcharge",
    "types": [
      "Grass",
      "Psychic"
    ],
    "cards": [
      {
        "id": "ex8-16",
        "name": "Deoxys",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "ex8-71",
        "name": "Seedot",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex8-43",
        "name": "Nuzleaf",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex8-25",
        "name": "Shiftry",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "ex8-67",
        "name": "Nincada",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex8-14",
        "name": "Shedinja",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "ex8-55",
        "name": "Beldum",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex8-40",
        "name": "Metang",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex8-76",
        "name": "Spoink",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex8-32",
        "name": "Grumpig",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex8-66",
        "name": "Natu",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex8-90",
        "name": "Professor Cozmo's Discovery",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex8-88",
        "name": "Master Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex6-101",
        "name": "Potion",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex1-90",
        "name": "Energy Search",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex8-89",
        "name": "Meteor Falls",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "ex1-104",
        "name": "Grass Energy",
        "rarity": "Common",
        "count": 16
      },
      {
        "id": "ex1-107",
        "name": "Psychic Energy",
        "rarity": "Common",
        "count": 8
      }
    ]
  },
  {
    "id": "d-ex8-2",
    "name": "Jetstream",
    "types": [
      "Fire",
      "Water",
      "Lightning"
    ],
    "cards": [
      {
        "id": "ex8-22",
        "name": "Rayquaza",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "ex8-63",
        "name": "Lotad",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex8-34",
        "name": "Lombre",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex8-19",
        "name": "Ludicolo",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "ex8-60",
        "name": "Electrike",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex8-38",
        "name": "Manectric",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex8-68",
        "name": "Numel",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex8-4",
        "name": "Camerupt",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "ex8-80",
        "name": "Taillow",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex8-49",
        "name": "Swellow",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "ex8-61",
        "name": "Goldeen",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex8-87",
        "name": "Lady Outing",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex8-88",
        "name": "Master Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex8-92",
        "name": "Strength Charm",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex6-102",
        "name": "Switch",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex6-101",
        "name": "Potion",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex1-106",
        "name": "Water Energy",
        "rarity": "Common",
        "count": 10
      },
      {
        "id": "ex1-109",
        "name": "Lightning Energy",
        "rarity": "Common",
        "count": 9
      },
      {
        "id": "ex1-108",
        "name": "Fire Energy",
        "rarity": "Common",
        "count": 5
      }
    ]
  }
]

=== PokemonTCG/pokemon-tcg-data/decks/en/xy8.json
[
  {
    "id": "d-xy8-1",
    "name": "Burning Spark",
    "types": [
      "Lightning",
      "Fire"
    ],
    "cards": [
      {
        "id": "xy8-49",
        "name": "Raichu",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "xy8-49",
        "name": "Raichu",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "xy8-48",
        "name": "Pikachu",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "xy8-54",
        "name": "Magnezone",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "xy8-53",
        "name": "Magneton",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "xy8-52",
        "name": "Magnemite",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "xy8-57",
        "name": "Dedenne",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "xy8-56",
        "name": "Stunfisk",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "xy8-26",
        "name": "Braixen",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "xy8-25",
        "name": "Fennekin",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "xy8-19",
        "name": "Quilava",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "xy8-18",
        "name": "Cyndaquil",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "xy8-23",
        "name": "Pansear",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "xy8-117",
        "name": "Dodrio",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "xy8-116",
        "name": "Doduo",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "xy8-123",
        "name": "Smeargle",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "xy8-136",
        "name": "Fisherman",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy8-138",
        "name": "Giovanni's Scheme",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy2-93",
        "name": "Pokémon Center Lady",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy2-94",
        "name": "Pokémon Fan Club",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy8-146",
        "name": "Professor's Letter",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "xy8-147",
        "name": "Reserved Ticket",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy8-149",
        "name": "Super Rod",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy8-148",
        "name": "Skyla",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy0-38",
        "name": "Switch",
        "count": 1
      },
      {
        "id": "xy4-107",
        "name": "Tierno",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy6-94",
        "name": "Wally",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy1-135",
        "name": "Lightning Energy",
        "count": 10
      },
      {
        "id": "xy1-133",
        "name": "Fire Energy",
        "count": 8
      }
    ]
  },
  {
    "id": "d-xy8-2",
    "name": "Night Striker",
    "types": [
      "Psychic",
      "Darkness"
    ],
    "cards": [
      {
        "id": "xy8-112",
        "name": "Noivern",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "xy8-112",
        "name": "Noivern",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "xy8-131",
        "name": "Noibat",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "xy8-60",
        "name": "Gengar",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "xy8-59",
        "name": "Haunter",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "xy8-58",
        "name": "Gastly",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "xy8-69",
        "name": "Kirlia",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "xy8-68",
        "name": "Ralts",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "xy8-70",
        "name": "Cresselia",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "xy8-65",
        "name": "Misdreavus",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "xy8-67",
        "name": "Wobbuffet",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "xy8-91",
        "name": "Zoroark",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "xy8-90",
        "name": "Zorua",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "xy8-93",
        "name": "Inkay",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "xy8-122",
        "name": "Ursaring",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "xy8-121",
        "name": "Teddiursa",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "xy8-136",
        "name": "Fisherman",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy8-138",
        "name": "Giovanni's Scheme",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy2-93",
        "name": "Pokémon Center Lady",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy2-94",
        "name": "Pokémon Fan Club",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy8-146",
        "name": "Professor's Letter",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "xy8-147",
        "name": "Reserved Ticket",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy8-148",
        "name": "Skyla",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy0-38",
        "name": "Switch",
        "count": 1
      },
      {
        "id": "xy4-107",
        "name": "Tierno",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "xy6-94",
        "name": "Wally",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "xy1-136",
        "name": "Psychic Energy",
        "count": 11
      },
      {
        "id": "xy1-138",
        "name": "Darkness Energy",
        "count": 7
      }
    ]
  }
]

=== PokemonTCG/pokemon-tcg-data/json/decks/Stormfront.json
[
    {
        "id": "d-dp7-1",
        "name": "Raging Sea",
        "types": [
            "Water",
            "Grass"
        ],
        "cards": [
            {
                "id": "dp7-19",
                "name": "Gyarados",
                "rarity": "Rare Holo",
                "count": 1
            },
            {
                "id": "dp7-65",
                "name": "Magikarp",
                "rarity": "Common",
                "count": 4
            },
            {
                "id": "dp7-10",
                "name": "Sceptile",
                "rarity": "Rare",
                "count": 1
            },
            {
                "id": "dp7-39",
                "name": "Grovyle",
                "rarity": "Uncommon",
                "count": 2
            },
            {
                "id": "dp7-79",
                "name": "Treecko",
                "rarity": "Common",
                "count": 4
            },
            {
                "id": "dp7-12",
                "name": "Abomasnow",
                "rarity": "Rare",
                "count": 1
            },
            {
                "id": "dp7-74",
                "name": "Snover",
                "rarity": "Common",
                "count": 4
            },
            {
                "id": "dp7-32",
                "name": "Bibarel",
                "rarity": "Uncommon",
                "count": 2
            },
            {
                "id": "dp7-54",
                "name": "Bidoof",
                "rarity": "Common",
                "count": 4
            },
            {
                "id": "dp7-61",
                "name": "Finneon",
                "rarity": "Common",
                "count": 2
            },
            {
                "id": "dp7-92",
                "name": "Potion",
                "rarity": "Common",
                "count": 2
            },
            {
                "id": "dp7-93",
                "name": "Switch",
                "rarity": "Common",
                "count": 2
            },
            {
                "id": "dp5-83",
                "name": "Mom's Kindness",
                "rarity": "Uncommon",
                "count": 2
            },
            {
                "id": "dp7-84",
                "name": "Energy Switch",
                "rarity": "Uncommon",
                "count": 2
            },
            {
                "id": "dp5-80",
                "name": "Dusk Ball",
                "rarity": "Uncommon",
                "count": 2
            },
            {
                "id": "dp7-86",
                "name": "Luxury Ball",
                "rarity": "Uncommon",
                "count": 1
            },
            {
                "id": "dp1-125",
                "name": "Water Energy",
                "count": 15
            },
            {
                "id": "dp1-123",
                "name": "Grass Energy",
                "count": 9
            }
        ]
    },
    {
        "id": "d-dp7-2",
        "name": "Dark Rampage",
        "types": [
            "Darkness",
            "Fighting"
        ],
        "cards": [
            {
                "id": "dp7-30",
                "name": "Tyranitar",
                "rarity": "Rare Holo",
                "count": 1
            },
            {
                "id": "dp7-47",
                "name": "Pupitar",
                "rarity": "Uncommon",
                "count": 2
            },
            {
                "id": "dp7-63",
                "name": "Larvitar",
                "rarity": "Common",
                "count": 4
            },
            {
                "id": "dp7-27",
                "name": "Staraptor",
                "rarity": "Rare",
                "count": 1
            },
            {
                "id": "dp7-52",
                "name": "Staravia",
                "rarity": "Uncommon",
                "count": 2
            },
            {
                "id": "dp7-75",
                "name": "Starly",
                "rarity": "Common",
                "count": 4
            },
            {
                "id": "dp7-26",
                "name": "Skuntank",
                "rarity": "Rare",
                "count": 1
            },
            {
                "id": "dp7-76",
                "name": "Stunky",
                "rarity": "Common",
                "count": 4
            },
            {
                "id": "dp7-64",
                "name": "Machop",
                "rarity": "Common",
                "count": 4
            },
            {
                "id": "dp7-53",
                "name": "Bagon",
                "rarity": "Common",
                "count": 2
            },
            {
                "id": "dp7-92",
                "name": "Potion",
                "rarity": "Common",
                "count": 2
            },
            {
                "id": "dp5-90",
                "name": "Energy Search",
                "rarity": "Common",
                "count": 2
            },
            {
                "id": "dp6-131",
                "name": "Cynthia's Feelings",
                "rarity": "Uncommon",
                "count": 2
            },
            {
                "id": "dp7-84",
                "name": "Energy Switch",
                "rarity": "Uncommon",
                "count": 2
            },
            {
                "id": "dp7-85",
                "name": "Great Ball",
                "rarity": "Uncommon",
                "count": 2
            },
            {
                "id": "dp7-86",
                "name": "Luxury Ball",
                "rarity": "Uncommon",
                "count": 1
            },
            {
                "id": "dp5-93",
                "name": "Darkness Energy",
                "count": 13
            },
            {
                "id": "dp1-128",
                "name": "Fighting Energy",
                "count": 11
            }
        ]
    }
]

=== PokemonTCG/pokemon-tcg-data/decks/en/pl2.json
[
  {
    "id": "d-pl2-1",
    "name": "Drill Point",
    "types": [
      "Fighting",
      "Water"
    ],
    "cards": [
      {
        "id": "pl2-32",
        "name": "Rhyperior",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "pl2-5",
        "name": "Flygon",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "pl2-53",
        "name": "Vibrava",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "pl2-84",
        "name": "Trapinch",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "pl2-42",
        "name": "Hippowdon",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "pl2-25",
        "name": "Hippowdon",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "pl2-64",
        "name": "Hippopotas",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "pl2-50",
        "name": "Starmie",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "pl2-83",
        "name": "Staryu",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "pl2-55",
        "name": "Aerodactyl",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "dp7-92",
        "name": "Potion",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "dp7-93",
        "name": "Switch",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "pl2-88",
        "name": "Aaron's Collection",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "pl2-89",
        "name": "Bebe's Search",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "dp4-98",
        "name": "Felicity's Drawing",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "pl2-98",
        "name": "Volkner's Philosophy",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "dp1-125",
        "name": "Water Energy",
        "count": 12
      },
      {
        "id": "dp1-128",
        "name": "Fighting Energy",
        "count": 12
      }
    ]
  },
  {
    "id": "d-pl2-2",
    "name": "Cutting Edge",
    "types": [
      "Psychic",
      "Grass"
    ],
    "cards": [
      {
        "id": "pl2-20",
        "name": "Gallade",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "pl2-15",
        "name": "Beedrill",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "pl2-66",
        "name": "Kakuna",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "pl2-86",
        "name": "Weedle",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "pl2-28",
        "name": "Mr. Mime",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "pl2-40",
        "name": "Gengar",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "pl2-45",
        "name": "Leafeon",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "pl2-59",
        "name": "Eevee",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "pl2-87",
        "name": "Weezing",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "pl2-68",
        "name": "Koffing",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "pl2-78",
        "name": "Seedot",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "dp5-90",
        "name": "Energy Search",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "dp7-92",
        "name": "Potion",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "pl2-88",
        "name": "Aaron's Collection",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "pl2-92",
        "name": "Lucian's Assignment",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "dp5-83",
        "name": "Mom's Kindness",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "pl2-97",
        "name": "Underground Expedition",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "dp1-123",
        "name": "Grass Energy",
        "count": 11
      },
      {
        "id": "dp1-127",
        "name": "Psychic Energy",
        "count": 13
      }
    ]
  }
]
