=== PokemonTCG/pokemon-tcg-data/decks/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": { "type": "string" },
      "name": { "type": "string" },
      "types": {
        "type": "array",
        "items": {
          "enum": [ 
            "Colorless",
            "Darkness",
            "Dragon",
            "Fairy",
            "Fire",
            "Fighting",
            "Grass",
            "Lightning",
            "Metal",
            "Psychic",
            "Water",
            "Free"
          ]
        }
      },
      "cards": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": { "type": "string" },
            "name": { "type": "string" },
            "rarity": {
              "enum": [
                "Common",
                "Common Holo",
                "Uncommon",
                "Uncommon Holo",
                "Rare",
                "Rare Holo",
                "Rare ACE",
                "Rare BREAK",
                "Rare Prime",
                "Rare Holo LV.X",
                "Rare Holo EX",
                "Rare Holo GX",
                "Rare Holo Star",
                "Rare Holo V",
                "Rare Holo VMAX",
                "Rare Holo VSTAR",
                "Rare Prism Star",
                "Rare Shining",
                "Rare Shiny",
                "Rare Shiny GX",
                "Rare Ultra",
                "Rare Rainbow",
                "Rare Secret",
                "Amazing Rare",
                "Radiant Rare",
                "LEGEND",
                "V",
                "VM",
                "Promo",
                "Classic Collection"
              ]
            },
            "count": { "type": "integer" }
          },
          "required": [ "id", "name", "count" ]
        }
      }
    },
    "required": [
      "id",
      "name",
      "types",
      "cards"
    ]
  }
}

=== PokemonTCG/pokemon-tcg-data/decks/en/bw2.json
[
  {
    "id": "d-bw2-1",
    "name": "Power Play",
    "types": [
      "Fighting",
      "Water"
    ],
    "cards": [
      {
        "id": "bw2-62",
        "name": "Krookodile",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "bw2-62",
        "name": "Krookodile",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw2-61",
        "name": "Krokorok",
        "rarity": "Uncommon",
        "count": 3
      },
      {
        "id": "bw2-60",
        "name": "Sandile",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "bw2-53",
        "name": "Gigalith",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw2-52",
        "name": "Boldore",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw2-50",
        "name": "Roggenrola",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "bw2-31",
        "name": "Beartic",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw2-29",
        "name": "Cubchoo",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw2-27",
        "name": "Swanna",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw2-26",
        "name": "Ducklett",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw2-85",
        "name": "Cinccino",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw2-84",
        "name": "Minccino",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw2-24",
        "name": "Basculin",
        "rarity": "Common",
        "count": 1
      },
      {
        "id": "bw2-58",
        "name": "Throh",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw2-59",
        "name": "Sawk",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw1-93",
        "name": "Energy Search",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw1-100",
        "name": "Potion",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw1-95",
        "name": "Full Heal",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw2-93",
        "name": "Great Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw1-99",
        "name": "Pokémon Communication",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw2-90",
        "name": "Bianca",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw1-110",
        "name": "Fighting Energy",
        "rarity": "Common",
        "count": 12
      },
      {
        "id": "bw1-107",
        "name": "Water Energy",
        "rarity": "Common",
        "count": 6
      }
    ]
  },
  {
    "id": "d-bw2-2",
    "name": "Toxic Tricks",
    "types": [
      "Psychic",
      "Fire"
    ],
    "cards": [
      {
        "id": "bw2-40",
        "name": "Scolipede",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "bw2-40",
        "name": "Scolipede",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw2-39",
        "name": "Whirlipede",
        "rarity": "Uncommon",
        "count": 3
      },
      {
        "id": "bw2-38",
        "name": "Venipede",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "bw2-48",
        "name": "Gothitelle",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw2-45",
        "name": "Gothorita",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw2-43",
        "name": "Gothita",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "bw2-21",
        "name": "Darmanitan",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw2-20",
        "name": "Darumaka",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw2-19",
        "name": "Simisear",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw2-18",
        "name": "Pansear",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw2-42",
        "name": "Sigilyph",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw2-81",
        "name": "Tranquill",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw2-80",
        "name": "Pidove",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "bw2-36",
        "name": "Woobat",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw1-93",
        "name": "Energy Search",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw1-104",
        "name": "Switch",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw1-92",
        "name": "Energy Retrieval",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw2-93",
        "name": "Great Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw1-99",
        "name": "Pokémon Communication",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw2-91",
        "name": "Cheren",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw1-109",
        "name": "Psychic Energy",
        "rarity": "Common",
        "count": 12
      },
      {
        "id": "bw1-106",
        "name": "Fire Energy",
        "rarity": "Common",
        "count": 6
      }
    ]
  }
]

=== PokemonTCG/pokemon-tcg-data/decks/en/swsh3.json
[
  {
    "id": "d-swsh3-1",
    "name": "Galarian Darmanitan",
    "types": [
      "Water"
    ],
    "cards": [
      {
        "id": "swsh3-44",
        "name": "Galarian Darmanitan",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "swsh3-44",
        "name": "Galarian Darmanitan",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "swsh3-28",
        "name": "Galarian Darmanitan",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "swsh3-43",
        "name": "Galarian Darumaka",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "swsh2-42",
        "name": "Pelipper",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh2-44",
        "name": "Wingull",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "swsh3-49",
        "name": "Beartic",
        "rarity": "Rare",
        "count": 2
      },
      {
        "id": "swsh3-48",
        "name": "Cubchoo",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "swsh3-50",
        "name": "Wishiwashi",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "swsh3-37",
        "name": "Suicune",
        "rarity": "Rare",
        "count": 2
      },
      {
        "id": "swsh3-133",
        "name": "Kangaskhan",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh1-157",
        "name": "Bede",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh3-159",
        "name": "Bird Keeper",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh2-156",
        "name": "Capacious Bucket",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh1-164",
        "name": "Great Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh1-165",
        "name": "Hop",
        "rarity": "Uncommon",
        "count": 4
      },
      {
        "id": "swsh1-178",
        "name": "Professor's Research",
        "rarity": "Rare",
        "count": 2
      },
      {
        "id": "swsh2-167",
        "name": "Sonia",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh1-183",
        "name": "Switch",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh3-172",
        "name": "Turbo Patch",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh1-0",
        "name": "Water Energy",
        "count": 18
      }
    ]
  },
  {
    "id": "d-swsh3-2",
    "name": "Galarian Sirfetch'd",
    "types": [
      "Fighting"
    ],
    "cards": [
      {
        "id": "swsh3-98",
        "name": "Galarian Sirfetch'd",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "swsh3-98",
        "name": "Galarian Sirfetch'd",
        "rarity": "Rare",
        "count": 2
      },
      {
        "id": "swsh2-94",
        "name": "Galarian Farfetch'd",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "swsh3-85",
        "name": "Dugtrio",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh3-84",
        "name": "Diglett",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "swsh3-94",
        "name": "Hippowdon",
        "rarity": "Rare",
        "count": 2
      },
      {
        "id": "swsh3-93",
        "name": "Hippopotas",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "swsh2-111",
        "name": "Stonjourner",
        "rarity": "Rare",
        "count": 2
      },
      {
        "id": "swsh1-100",
        "name": "Sudowoodo",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh3-97",
        "name": "Passimian",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "swsh1-157",
        "name": "Bede",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh3-159",
        "name": "Bird Keeper",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh1-164",
        "name": "Great Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh1-165",
        "name": "Hop",
        "rarity": "Uncommon",
        "count": 4
      },
      {
        "id": "swsh1-175",
        "name": "Pok√©mon Catcher",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh1-178",
        "name": "Professor's Research",
        "rarity": "Rare",
        "count": 2
      },
      {
        "id": "swsh2-167",
        "name": "Sonia",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh1-183",
        "name": "Switch",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh3-172",
        "name": "Turbo Patch",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "swsh1-0",
        "name": "Fighting Energy",
        "count": 18
      }
    ]
  }
]

=== PokemonTCG/pokemon-tcg-data/decks/en/bw3.json
[
  {
    "id": "d-bw3-1",
    "name": "Fast Daze",
    "types": [
      "Grass",
      "Fire"
    ],
    "cards": [
      {
        "id": "bw3-12",
        "name": "Accelgor",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "bw3-12",
        "name": "Accelgor",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw3-11",
        "name": "Shelmet",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "bw3-3",
        "name": "Leavanny",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw3-2",
        "name": "Swadloon",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw3-1",
        "name": "Sewaddle",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "bw3-5",
        "name": "Lilligant",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw3-4",
        "name": "Petilil",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw3-7",
        "name": "Crustle",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw3-6",
        "name": "Dwebble",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw3-9",
        "name": "Foongus",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "bw3-21",
        "name": "Volcarona",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw3-20",
        "name": "Larvesta",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw3-17",
        "name": "Simisear",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw3-16",
        "name": "Pansear",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw1-93",
        "name": "Energy Search",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw1-100",
        "name": "Potion",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw2-91",
        "name": "Cheren",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw2-93",
        "name": "Great Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw3-92",
        "name": "N",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "bw1-99",
        "name": "Pokémon Communication",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw3-95",
        "name": "Super Rod",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw1-105",
        "name": "Grass Energy",
        "rarity": "Common",
        "count": 12
      },
      {
        "id": "bw1-106",
        "name": "Fire Energy",
        "rarity": "Common",
        "count": 6
      }
    ]
  },
  {
    "id": "d-bw3-2",
    "name": "Furious Knights",
    "types": [
      "Metal",
      "Lightning"
    ],
    "cards": [
      {
        "id": "bw3-80",
        "name": "Escavalier",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "bw3-80",
        "name": "Escavalier",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw3-8",
        "name": "Karrablast",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "bw3-83",
        "name": "Durant",
        "rarity": "Uncommon",
        "count": 3
      },
      {
        "id": "bw3-41",
        "name": "Eelektross",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw3-40",
        "name": "Eelektrik",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw3-39",
        "name": "Tynamo",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "bw3-36",
        "name": "Zebstrika",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw3-35",
        "name": "Blitzle",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw3-37",
        "name": "Emolga",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw3-42",
        "name": "Stunfisk",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw3-89",
        "name": "Druddigon",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "bw3-85",
        "name": "Audino",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw3-87",
        "name": "Fraxure",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw3-86",
        "name": "Axew",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw1-93",
        "name": "Energy Search",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw1-104",
        "name": "Switch",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "bw2-90",
        "name": "Bianca",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw2-93",
        "name": "Great Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw3-92",
        "name": "N",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "bw1-99",
        "name": "Pokémon Communication",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw3-95",
        "name": "Super Rod",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "bw1-108",
        "name": "Lightning Energy",
        "rarity": "Common",
        "count": 12
      },
      {
        "id": "bw1-112",
        "name": "Metal Energy",
        "rarity": "Common",
        "count": 6
      }
    ]
  }
]

=== PokemonTCG/pokemon-tcg-data/decks/en/neo2.json
[
  {
    "id": "d-neo2-1",
    "name": "BrainWave",
    "types": [
      "Psychic",
      "Water"
    ],
    "cards": [
      {
        "id": "neo2-38",
        "name": "Eevee",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "neo2-20",
        "name": "Espeon",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "neo1-58",
        "name": "Girafarig",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "neo2-59",
        "name": "Natu",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "neo2-52",
        "name": "Xatu",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "neo2-14",
        "name": "Unown A",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "neo2-68",
        "name": "Unown I",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "neo2-50",
        "name": "Unown N",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "neo1-64",
        "name": "Mantine",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "neo1-66",
        "name": "Marill",
        "rarity": "Common",
        "count": 1
      },
      {
        "id": "neo2-60",
        "name": "Omanyte",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "neo2-43",
        "name": "Omastar",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "neo2-65",
        "name": "Teddiursa",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "neo2-75",
        "name": "Energy Ark",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "neo2-72",
        "name": "Fossil Egg",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "neo1-101",
        "name": "Moo-Moo Milk",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "neo1-96",
        "name": "Professor Elm",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "neo1-110",
        "name": "Psychic Energy",
        "count": 16
      },
      {
        "id": "neo1-111",
        "name": "Water Energy",
        "count": 12
      }
    ]
  },
  {
    "id": "d-neo2-2",
    "name": "Wallop",
    "types": [
      "Grass",
      "Fighting"
    ],
    "cards": [
      {
        "id": "neo2-57",
        "name": "Larvitar",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "neo2-45",
        "name": "Pupitar",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "neo2-66",
        "name": "Tyrogue",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "neo2-3",
        "name": "Hitmontop",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "neo2-63",
        "name": "Sentret",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "neo2-53",
        "name": "Caterpie",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "neo2-42",
        "name": "Metapod",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "neo2-19",
        "name": "Butterfree",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "neo2-46",
        "name": "Scyther",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "neo1-100",
        "name": "Double Gust",
        "rarity": "Common",
        "count": 1
      },
      {
        "id": "neo2-75",
        "name": "Energy Ark",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "neo2-73",
        "name": "Hyper Devolution Spray",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "neo1-101",
        "name": "Moo-Moo Milk",
        "rarity": "Common",
        "count": 1
      },
      {
        "id": "neo1-96",
        "name": "Professor Elm",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "neo1-103",
        "name": "Super Rod",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "neo1-106",
        "name": "Fighting Energy",
        "count": 12
      },
      {
        "id": "neo1-108",
        "name": "Grass Energy",
        "count": 16
      }
    ]
  }
]
