=== PokemonTCG/pokemon-tcg-data/decks/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": { "type": "string" },
      "name": { "type": "string" },
      "types": {
        "type": "array",
        "items": {
          "enum": [ 
            "Colorless",
            "Darkness",
            "Dragon",
            "Fairy",
            "Fire",
            "Fighting",
            "Grass",
            "Lightning",
            "Metal",
            "Psychic",
            "Water",
            "Free"
          ]
        }
      },
      "cards": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": { "type": "string" },
            "name": { "type": "string" },
            "rarity": {
              "enum": [
                "Common",
                "Common Holo",
                "Uncommon",
                "Uncommon Holo",
                "Rare",
                "Rare Holo",
                "Rare ACE",
                "Rare BREAK",
                "Rare Prime",
                "Rare Holo LV.X",
                "Rare Holo EX",
                "Rare Holo GX",
                "Rare Holo Star",
                "Rare Holo V",
                "Rare Holo VMAX",
                "Rare Holo VSTAR",
                "Rare Prism Star",
                "Rare Shining",
                "Rare Shiny",
                "Rare Shiny GX",
                "Rare Ultra",
                "Rare Rainbow",
                "Rare Secret",
                "Amazing Rare",
                "Radiant Rare",
                "LEGEND",
                "V",
                "VM",
                "Promo",
                "Classic Collection"
              ]
            },
            "count": { "type": "integer" }
          },
          "required": [ "id", "name", "count" ]
        }
      }
    },
    "required": [
      "id",
      "name",
      "types",
      "cards"
    ]
  }
}

=== PokemonTCG/pokemon-tcg-data/decks/en/hgss1.json
[
  {
    "id": "d-hgss1-1",
    "name": "Growth Clash",
    "types": [
      "Grass",
      "Fighting"
    ],
    "cards": [
      {
        "id": "hgss1-26",
        "name": "Meganium",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "hgss1-35",
        "name": "Bayleef",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-59",
        "name": "Chikorita",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "hgss1-21",
        "name": "Furret",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "hgss1-80",
        "name": "Sentret",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "hgss1-29",
        "name": "Sandslash",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "hgss1-79",
        "name": "Sandshrew",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "hgss1-46",
        "name": "Metapod",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-57",
        "name": "Caterpie",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "hgss1-75",
        "name": "Meowth",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "hgss1-89",
        "name": "Bill",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-94",
        "name": "Moomoo Milk",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "hgss1-98",
        "name": "Pokémon Communication",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-99",
        "name": "Pokémon Reversal",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-102",
        "name": "Switch",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "hgss1-101",
        "name": "Professor Oak's New Theory",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "hgss1-95",
        "name": "Poké Ball",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "hgss1-115",
        "name": "Grass Energy",
        "rarity": "Common",
        "count": 13
      },
      {
        "id": "hgss1-120",
        "name": "Fighting Energy",
        "rarity": "Common",
        "count": 11
      }
    ]
  },
  {
    "id": "d-hgss1-2",
    "name": "Ember Spark",
    "types": [
      "Fire",
      "Lightning"
    ],
    "cards": [
      {
        "id": "hgss1-32",
        "name": "Typhlosion",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "hgss1-49",
        "name": "Quilava",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-61",
        "name": "Cyndaquil",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "hgss1-1",
        "name": "Arcanine",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "hgss1-65",
        "name": "Growlithe",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "hgss1-8",
        "name": "Noctowl",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "hgss1-66",
        "name": "Hoothoot",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "hgss1-42",
        "name": "Flaaffy",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-73",
        "name": "Mareep",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "hgss1-78",
        "name": "Pikachu",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "hgss1-90",
        "name": "Copycat",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "hgss1-94",
        "name": "Moomoo Milk",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-98",
        "name": "Pokémon Communication",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-99",
        "name": "Pokémon Reversal",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-101",
        "name": "Professor Oak's New Theory",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-102",
        "name": "Switch",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-116",
        "name": "Fire Energy",
        "rarity": "Common",
        "count": 14
      },
      {
        "id": "hgss1-118",
        "name": "Lightning Energy",
        "rarity": "Common",
        "count": 10
      }
    ]
  },
  {
    "id": "d-hgss1-3",
    "name": "Mind Flood",
    "types": [
      "Water",
      "Psychic"
    ],
    "cards": [
      {
        "id": "hgss1-20",
        "name": "Feraligatr",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "hgss1-38",
        "name": "Croconaw",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-86",
        "name": "Totodile",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "hgss1-18",
        "name": "Exeggutor",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "hgss1-63",
        "name": "Exeggcute",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "hgss1-23",
        "name": "Hypno",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "hgss1-62",
        "name": "Drowzee",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "hgss1-52",
        "name": "Slowbro",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-81",
        "name": "Slowpoke",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "hgss1-69",
        "name": "Jynx",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "hgss1-89",
        "name": "Bill",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-93",
        "name": "Full Heal",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "hgss1-95",
        "name": "Poké Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-100",
        "name": "Professor Elm's Training Method",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-101",
        "name": "Professor Oak's New Theory",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-94",
        "name": "Moomoo Milk",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "hgss1-117",
        "name": "Water Energy",
        "rarity": "Common",
        "count": 13
      },
      {
        "id": "hgss1-119",
        "name": "Psychic Energy",
        "rarity": "Common",
        "count": 11
      }
    ]
  }
]

=== PokemonTCG/pokemon-tcg-data/decks/en/ex14.json
[
  {
    "id": "d-ex14-1",
    "name": "Green Cyclone",
    "types": [
      "Grass"
    ],
    "cards": [
      {
        "id": "ex14-45",
        "name": "Bulbasaur",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex14-34",
        "name": "Ivysaur",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-28",
        "name": "Venusaur",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "ex14-69",
        "name": "Whismur",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex14-23",
        "name": "Loudred",
        "rarity": "Rare",
        "count": 2
      },
      {
        "id": "ex14-67",
        "name": "Treecko",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex14-32",
        "name": "Grovyle",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-60",
        "name": "Seedot",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex14-53",
        "name": "Jigglypuff",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex14-33",
        "name": "Gulpin",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "ex14-73",
        "name": "Celio's Network",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-78",
        "name": "Dual Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-86",
        "name": "Energy Search",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex12-73",
        "name": "Fieldworker",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-87",
        "name": "Potion",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex13-105",
        "name": "Grass Energy",
        "count": 24
      }
    ]
  },
  {
    "id": "d-ex14-2",
    "name": "Storm Surge",
    "types": [
      "Water",
      "Lightning"
    ],
    "cards": [
      {
        "id": "ex14-63",
        "name": "Squirtle",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex14-43",
        "name": "Wartortle",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-14",
        "name": "Blastoise",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "ex14-61",
        "name": "Spearow",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex14-18",
        "name": "Fearow δ",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "ex14-70",
        "name": "Wingull",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex14-26",
        "name": "Pelipper δ",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "ex14-49",
        "name": "Charmander δ",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex14-30",
        "name": "Charmeleon δ",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-54",
        "name": "Krabby",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex14-71",
        "name": "Bill's Maintenance",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-77",
        "name": "Double Full Heal",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "ex14-86",
        "name": "Energy Search",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex14-82",
        "name": "Poké Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-87",
        "name": "Potion",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex14-84",
        "name": "Warp Point",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex13-108",
        "name": "Lightning Energy",
        "count": 13
      },
      {
        "id": "ex13-107",
        "name": "Water Energy",
        "count": 11
      }
    ]
  },
  {
    "id": "d-ex14-3",
    "name": "Earth Shower",
    "types": [
      "Water",
      "Fighting"
    ],
    "cards": [
      {
        "id": "ex14-58",
        "name": "Mudkip",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex14-38",
        "name": "Marshtomp",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-27",
        "name": "Swampert",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "ex14-50",
        "name": "Diglett",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex14-5",
        "name": "Dugtrio",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "ex14-56",
        "name": "Meditite",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex14-25",
        "name": "Medicham",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "ex14-44",
        "name": "Aron",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex14-36",
        "name": "Lairon",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-55",
        "name": "Lotad",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex14-71",
        "name": "Bill's Maintenance",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-73",
        "name": "Celio's Network",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-86",
        "name": "Energy Search",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex14-83",
        "name": "PokéNav",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-87",
        "name": "Potion",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex14-84",
        "name": "Warp Point",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "ex13-110",
        "name": "Fighting Energy",
        "count": 13
      },
      {
        "id": "ex13-107",
        "name": "Water Energy",
        "count": 9
      },
      {
        "id": "ex13-95",
        "name": "Metal Energy",
        "rarity": "Rare",
        "count": 2
      }
    ]
  }
]

=== PokemonTCG/pokemon-tcg-data/decks/en/sm3.json
[
  {
    "id": "d-sm3-1",
    "name": "Rock Steady",
    "types": [
      "Fighting",
      "Psychic"
    ],
    "cards": [
      {
        "id": "sm3-76",
        "name": "Lycanroc",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "sm3-76",
        "name": "Lycanroc",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "sm2-73",
        "name": "Rockruff",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "sm3-67",
        "name": "Rhyperior",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "sm3-66",
        "name": "Rhydon",
        "rarity": "Uncommon",
        "count": 3
      },
      {
        "id": "sm3-65",
        "name": "Rhyhorn",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "sm3-71",
        "name": "Lucario",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "sm3-70",
        "name": "Riolu",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "sm3-69",
        "name": "Solrock",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "sm3-72",
        "name": "Sawk",
        "rarity": "Common",
        "count": 1
      },
      {
        "id": "sm3-60",
        "name": "Meowstic",
        "rarity": "Rare",
        "count": 2
      },
      {
        "id": "sm3-59",
        "name": "Espurr",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "sm3-108",
        "name": "Bouffalant",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm3-112",
        "name": "Acerola",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm2-120",
        "name": "Brooklet Hill",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm1-116",
        "name": "Energy Retrieval",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm3-114",
        "name": "Escape Rope",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm1-120",
        "name": "Hau",
        "rarity": "Uncommon",
        "count": 3
      },
      {
        "id": "sm1-123",
        "name": "Nest Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "sm1-127",
        "name": "Potion",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm1-128",
        "name": "Professor Kukui",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "sm2-130",
        "name": "Rescue Stretcher",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm1-134",
        "name": "Timer Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "sm3-128",
        "name": "Wishful Baton",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm1-162",
        "name": "Psychic Energy",
        "count": 6
      },
      {
        "id": "sm2-169",
        "name": "Fighting Energy",
        "count": 14
      }
    ]
  },
  {
    "id": "d-sm3-2",
    "name": "Luminous Frost",
    "types": [
      "Water",
      "Fire"
    ],
    "cards": [
      {
        "id": "sm3-28",
        "name": "Alolan Ninetales",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "sm3-28",
        "name": "Alolan Ninetales",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "sm3-27",
        "name": "Alolan Vulpix",
        "rarity": "Common",
        "count": 3
      },
      {
        "id": "sm3-31",
        "name": "Kingdra",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "sm3-30",
        "name": "Seadra",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "sm3-29",
        "name": "Horsea",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "sm2-20",
        "name": "Alolan Sandslash",
        "rarity": "Rare",
        "count": 2
      },
      {
        "id": "sm2-19",
        "name": "Alolan Sandshrew",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "sm3-37",
        "name": "Simipour",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "sm3-36",
        "name": "Panpour",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "sm3-38",
        "name": "Bruxish",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "sm3-23",
        "name": "Simisear",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm3-22",
        "name": "Pansear",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "sm3-24",
        "name": "Heatmor",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "sm3-108",
        "name": "Bouffalant",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm1-114",
        "name": "Big Malasada",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm1-116",
        "name": "Energy Retrieval",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm3-114",
        "name": "Escape Rope",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm1-120",
        "name": "Hau",
        "rarity": "Uncommon",
        "count": 3
      },
      {
        "id": "sm3-117",
        "name": "Lana",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm1-123",
        "name": "Nest Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "sm1-128",
        "name": "Professor Kukui",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "sm2-130",
        "name": "Rescue Stretcher",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm1-134",
        "name": "Timer Ball",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "sm3-128",
        "name": "Wishful Baton",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "sm3-167",
        "name": "Fire Energy",
        "count": 6
      },
      {
        "id": "sm1-166",
        "name": "Water Energy",
        "count": 14
      }
    ]
  }
]

=== PokemonTCG/pokemon-tcg-data/decks/en/ex16.json
[
  {
    "id": "d-ex16-1",
    "name": "Mind Game",
    "types": [
      "Fighting",
      "Psychic"
    ],
    "cards": [
      {
        "id": "ex16-14",
        "name": "Dusclops",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "ex16-50",
        "name": "Duskull",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex16-9",
        "name": "Gardevoir",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "ex16-31",
        "name": "Kirlia",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex16-59",
        "name": "Ralts",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex16-33",
        "name": "Machoke",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex16-53",
        "name": "Machop",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex16-22",
        "name": "Sableye",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "ex16-55",
        "name": "Meditite",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex16-63",
        "name": "Slakoth",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex16-75",
        "name": "Energy Switch",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex16-78",
        "name": "Master Ball",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "ex16-80",
        "name": "Professor Birch",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "ex16-81",
        "name": "Scott",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "ex16-79",
        "name": "Phoebe's Stadium",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-86",
        "name": "Energy Search",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex14-87",
        "name": "Potion",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex16-107",
        "name": "Psychic Energy",
        "count": 14
      },
      {
        "id": "ex16-108",
        "name": "Fighting Energy",
        "count": 10
      }
    ]
  },
  {
    "id": "d-ex16-2",
    "name": "Dark Blast",
    "types": [
      "Darkness",
      "Fire"
    ],
    "cards": [
      {
        "id": "ex16-18",
        "name": "Mightyena",
        "rarity": "Rare Holo",
        "count": 1
      },
      {
        "id": "ex16-58",
        "name": "Poochyena",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex16-28",
        "name": "Charmeleon",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex16-48",
        "name": "Charmander",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex16-29",
        "name": "Combusken",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex16-67",
        "name": "Torchic",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex16-25",
        "name": "Zangoose",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "ex16-8",
        "name": "Delcatty",
        "rarity": "Rare",
        "count": 1
      },
      {
        "id": "ex16-62",
        "name": "Skitty",
        "rarity": "Common",
        "count": 4
      },
      {
        "id": "ex16-43",
        "name": "Bagon",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex16-74",
        "name": "Energy Removal 2",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex16-78",
        "name": "Master Ball",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "ex16-80",
        "name": "Professor Birch",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "ex16-81",
        "name": "Scott",
        "rarity": "Uncommon",
        "count": 1
      },
      {
        "id": "ex16-82",
        "name": "Sidney's Stadium",
        "rarity": "Uncommon",
        "count": 2
      },
      {
        "id": "ex14-86",
        "name": "Energy Search",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex14-87",
        "name": "Potion",
        "rarity": "Common",
        "count": 2
      },
      {
        "id": "ex16-87",
        "name": "Darkness Energy",
        "rarity": "Rare",
        "count": 4
      },
      {
        "id": "ex16-104",
        "name": "Fire Energy",
        "count": 20
      }
    ]
  }
]
